import {chromium} from 'playwright';import assert from 'node:assert/strict';import {testGame} from '@rarefriends/friendsdk/testing';
const launch=chromium.launch.bind(chromium);if(process.env.INVADERS_CHROMIUM)chromium.launch=o=>launch({...o,executablePath:process.env.INVADERS_CHROMIUM});
for(const [width,height] of (process.env.INVADERS_SIZE?JSON.parse(process.env.INVADERS_SIZE):[[320,568],[390,844],[844,390],[960,640]]))console.log(await testGame('./games/rare-invaders',{width,height,screenshot:`./artifacts/invaders-mobile-${width}.png`,check:async({page,game})=>{
 await page.clock.install();await page.reload();await page.getByRole('button',{name:/^Connect (wallet|Browser wallet)$/}).click();await page.getByRole('button',{name:/^Friend #7730/}).click();
 await game.getByRole('button',{name:'出撃する',exact:true}).click();
 const fire=await game.getByRole('button',{name:'射撃',exact:true}).boundingBox();const wallet=await page.getByRole('button',{name:'Open Friend wallet',exact:true}).boundingBox();assert.ok(fire.y+fire.height<=wallet.y,'game controls must not overlap host controls');assert.ok(wallet.y+wallet.height<=height,'host controls within screen');assert.ok(fire.height>=44);
 await game.getByRole('button',{name:'射撃',exact:true}).hover();await page.mouse.down();await page.clock.runFor(5000);await page.mouse.up();assert.ok(Number(await game.getByTestId('score').innerText())>0,'held touch control fires and scores');
 for(let elapsed=0;elapsed<180000;elapsed+=10000){await page.clock.runFor(10000);if(await game.getByRole('heading',{name:'TRY AGAIN',exact:true}).count())break;}

 await game.getByRole('heading',{name:'TRY AGAIN',exact:true}).waitFor();const finalScore=Number(await game.getByTestId('score').innerText());await game.getByRole('button',{name:'スコアをXでシェア',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'スコアをシェア',exact:true});await dialog.waitFor();await page.screenshot({path:`./artifacts/invaders-share-${width}.png`});const link=dialog.getByRole('link',{name:'Xの投稿画面を開く ↗'});const u=new URL(await link.getAttribute('href'));assert.equal(u.origin,'https://x.com');assert.ok(u.searchParams.get('text').includes(`Friend #7730と${finalScore}点`));assert.equal(u.searchParams.get('url'),'https://horusuzu.github.io/rare-friends-lost-and-found/invaders/');
 await page.context().route('https://x.com/**',r=>r.fulfill({body:'Test composer; no post sent'}));const popup=page.waitForEvent('popup');await link.click();const opened=await popup;await opened.waitForLoadState();assert.equal(new URL(opened.url()).origin,'https://x.com');await opened.close();if(width===320){await game.locator('body').evaluate(()=>location.reload());await dialog.waitFor({state:'hidden'});await game.getByRole('button',{name:'出撃する',exact:true}).click();}else{await dialog.getByRole('button',{name:'ゲームに戻る'}).click();await game.getByRole('button',{name:'もう一度',exact:true}).click();}
 assert.equal(await game.locator('.arcade').evaluate(e=>e.scrollHeight>e.clientHeight+1||e.scrollWidth>e.clientWidth+1),false);
}}));
