import test from 'node:test';
import assert from 'node:assert/strict';
import * as identity from '../dist/identity.js';
import * as sprites from '../dist/friend-sprites.js';
import {readFriendRewards,REWARDS_DEPLOYMENT as D} from '../dist/friend-rewards.js';
const owner='0x1111111111111111111111111111111111111111',wallet='0x2222222222222222222222222222222222222222';
function fixture(overrides={}){const calls=[];return {calls,getChainId:async()=>4663,getBlockNumber:async()=>123n,readContract:async r=>{calls.push(r);if(r.functionName==='generation')throw Error('Genesis has no generation');if(r.functionName in overrides){const v=overrides[r.functionName];if(v instanceof Error)throw v;return v;}return {ownerOf:owner,tokenBoundAccount:wallet,activationManager:D.manager,positions:[0,2000000n],retired:false,rf:D.rf,weth:D.weth,earned:7n,balanceOf:2n}[r.functionName];}};}
test('Genesis checks fresh owner and canonical wallet without Generations eligibility',async()=>{const c=fixture();const r=await identity.readGenesisEligibility(c,597n,owner);assert.equal(r.eligible,true);assert.equal(r.walletAddress,wallet);assert.equal(r.blockNumber,123n);assert.ok(c.calls.every(r=>r.address===D.genesis&&r.blockNumber===123n));});
test('Genesis rejects invalid inputs, wrong chain, invalid wallet and read failures; non-owner is ineligible',async()=>{for(const id of [0n,1n<<256n])await assert.rejects(()=>identity.readGenesisEligibility(fixture(),id,owner));await assert.rejects(()=>identity.readGenesisEligibility(fixture(),597n,'bad'));const c=fixture();c.getChainId=async()=>1;await assert.rejects(()=>identity.readGenesisEligibility(c,597n,owner));for(const v of ['0x0000000000000000000000000000000000000000','bad',new Error('RPC')])await assert.rejects(()=>identity.readGenesisEligibility(fixture({tokenBoundAccount:v}),597n,owner));assert.equal((await identity.readGenesisEligibility(fixture({ownerOf:wallet}),597n,owner)).eligible,false);});
test('selected Genesis rewards use Genesis collection exactly once, never linked duplicate or Generations',async()=>{const c=fixture();const r=await readFriendRewards(c,{friendId:597n,collection:'genesis',account:owner,walletAddress:wallet,genesisId:597n});assert.equal(r.collection,'genesis');assert.equal(r.genesis,undefined);assert.equal(r.claimableRF,7n);assert.ok(c.calls.filter(r=>r.functionName==='earned').every(r=>r.args[1]===D.genesis));await assert.rejects(()=>readFriendRewards(fixture({ownerOf:wallet}),{friendId:597n,collection:'genesis',account:owner,walletAddress:wallet}));});
const uri=properties=>'data:application/json;base64,'+Buffer.from(JSON.stringify({properties})).toString('base64');
test('Genesis canonical white-bit pixels become a doubled 16px portrait, not a Generations sprite',()=>{const art=sprites.decodeGenesisArtwork(597n,uri({pixels:'0x007e3c665a5a7e00',bit_order:'bit(y*8+x)=white',border_pixels:1}));assert.equal(art.collection,'genesis');assert.equal(art.tokenId,597n);assert.equal(art.familyName,'Genesis');assert.equal(art.clips.idle.down[0].rows[0],'################');assert.equal(art.clips.idle.down[0].rows[2],'##............##');});
test('Genesis artwork fails explicitly for unsupported metadata',()=>{for(const raw of ['https://example.com',uri({}),uri({pixels:'0x123',bit_order:'wrong'})])assert.throws(()=>sprites.decodeGenesisArtwork(597n,raw));});
test('Genesis artwork reader rejects wrong chain and IDs and reads only canonical tokenURI',async()=>{
 const metadata=uri({pixels:'0x007e3c665a5a7e00',bit_order:'bit(y*8+x)=white',border_pixels:1});const c=fixture({tokenURI:metadata});assert.equal((await sprites.readGenesisArtwork(c,597n)).collection,'genesis');assert.equal(c.calls[0].address,D.genesis);assert.equal(c.calls[0].functionName,'tokenURI');
 await assert.rejects(()=>sprites.readGenesisArtwork(c,0n));c.getChainId=async()=>1;await assert.rejects(()=>sprites.readGenesisArtwork(c,597n));
});
